# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/g2-common/setup-makefiles.sh


## Copy blobs
# bin
PRODUCT_COPY_FILES += \
	vendor/lge/msm8974-common/proprietary/bin/irsc_util:system/bin/irsc_util \
	vendor/lge/msm8974-common/proprietary/bin/mpdecision:system/bin/mpdecision \
	vendor/lge/msm8974-common/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/lge/msm8974-common/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/lge/msm8974-common/proprietary/bin/qseecomd:system/bin/qseecomd \
	vendor/lge/msm8974-common/proprietary/bin/radish:system/bin/radish \
	vendor/lge/msm8974-common/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/lge/msm8974-common/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
	vendor/lge/msm8974-common/proprietary/bin/time_daemon:system/bin/time_daemon

# etc
PRODUCT_COPY_FILES += \
	vendor/lge/msm8974-common/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
	vendor/lge/msm8974-common/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
	vendor/lge/msm8974-common/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
	vendor/lge/msm8974-common/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml

# lib
PRODUCT_COPY_FILES += \
	vendor/lge/msm8974-common/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
	vendor/lge/msm8974-common/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
	vendor/lge/msm8974-common/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
	vendor/lge/msm8974-common/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
	vendor/lge/msm8974-common/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	vendor/lge/msm8974-common/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
	vendor/lge/msm8974-common/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
	vendor/lge/msm8974-common/proprietary/lib/libmmQSM.so:system/lib/libmmQSM.so \
	vendor/lge/msm8974-common/proprietary/lib/liboemcrypto.so:system/lib/liboemcrypto.so \
	vendor/lge/msm8974-common/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
	vendor/lge/msm8974-common/proprietary/lib/librpmb.so:system/lib/librpmb.so \
	vendor/lge/msm8974-common/proprietary/lib/libssd.so:system/lib/libssd.so \
	vendor/lge/msm8974-common/proprietary/lib/libvss_common_core.so:system/lib/libvss_common_core.so \
	vendor/lge/msm8974-common/proprietary/lib/libvss_common_idl.so:system/lib/libvss_common_idl.so \
	vendor/lge/msm8974-common/proprietary/lib/libvss_common_iface.so:system/lib/libvss_common_iface.so \
	vendor/lge/msm8974-common/proprietary/lib/libvss_nv_core.so:system/lib/libvss_nv_core.so \
	vendor/lge/msm8974-common/proprietary/lib/libvss_nv_idl.so:system/lib/libvss_nv_idl.so \
	vendor/lge/msm8974-common/proprietary/lib/libvss_nv_iface.so:system/lib/libvss_nv_iface.so \
	vendor/lge/msm8974-common/proprietary/lib/libxml.so:system/lib/libxml.so

# lib subfolders
PRODUCT_COPY_FILES += \
	vendor/lge/msm8974-common/proprietary/lib/hw/flp.msm8974.so:system/vendor/lib/flp.msm8974.so \
	vendor/lge/msm8974-common/proprietary/lib/hw/sensors.msm8974.so:system/vendor/lib/sensors.msm8974.so

# vendor/lib
PRODUCT_COPY_FILES += \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libaptX-1.0.0-rel-Android21-ARMv7A.so:system/vendor/lib/libaptX-1.0.0-rel-Android21-ARMv7A.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libaptXScheduler.so:system/vendor/lib/libaptXScheduler.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libuiblur.so:system/vendor/lib/libuiblur.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so

# vendor/lib subfolders
PRODUCT_COPY_FILES += \
	vendor/lge/msm8974-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/egl/libplayback_adreno.so:system/vendor/lib/egl/libplayback_adreno.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
	vendor/lge/msm8974-common/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

## Packages	
PRODUCT_PACKAGES += \
	TimeService \
	libtime_genoff \
	qcrilmsgtunnel \
	shutdownlistener \
	qcrilhook
